# Folders with input and output data
input_dir: input
output_dir: output

# Options for read filtering
# If a read is multimapped, only the primary alignment will be considered
primary: True
# If a read is multimapped, all its alignments will be ignored
unique: False

# Read pair orientation corresponding to forward strand in strand-specific protocols
forward_strand: F2R1
# F2 means that read2 is on the forward strand, R1 - read1 on the reverse strand
# Possible values: F2R1, F1R2
# In Illumina strand-specific protocol it's usually F2R1

# Minimal offset when aggregating all offsets
min_offset: 4

# Minimal intron length
min_intron_length: 40


anno_urls:
  hg19: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/GRCh37_mapping/gencode.v35lift37.annotation.gtf.gz
  hg38: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.primary_assembly.annotation.gtf.gz
  mm10: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.primary_assembly.annotation.gtf.gz
  mm9: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M1/gencode.vM1.annotation.gtf.gz
  dm6: http://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/genes/dm6.ensGene.gtf.gz
  dm3: http://hgdownload.soe.ucsc.edu/goldenPath/dm3/bigZips/genes/dm3.ensGene.gtf.gz


genome_urls:
  hg19: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz
  hg38: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/GRCh38.primary_assembly.genome.fa.gz
  mm10: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/GRCm38.primary_assembly.genome.fa.gz
  mm9: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M1/NCBIM37.genome.fa.gz
  dm6: http://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz
  dm3: http://hgdownload.soe.ucsc.edu/goldenPath/dm3/bigZips/dm3.fa.gz